- hosts: docker
  vars_files:
  - ../vars/main.yml
  remote_user: root  
  tasks:
    - name: Check Docker Process
      shell: docker ps | grep {{ CONTAINER_NAME }}
      register: result
      failed_when: result.rc not in [0, 1]

    - name: STOP EAP Docker Container
      command: docker stop {{ CONTAINER_NAME }}
      when: result.rc == 0

    - name: Create EAP Docker Image
      command: docker commit {{ CONTAINER_NAME }} {{ EAP_IMAGE_NAME }}

    - name: Add tag to EAP Docker Image
      command: docker tag -f {{ EAP_IMAGE_NAME }} {{ DOCKER_REGISTRY }}/{{ EAP_IMAGE_NAME }} 

    - name: Push Image to Registry
      command: docker push {{ DOCKER_REGISTRY }}/{{ EAP_IMAGE_NAME }}

